export azure_connection_string="DefaultEndpointsProtocol=https;AccountName=dhanujaexl;AccountKey=Srz4Z3s0MOBtupU6/Vk1XbJXC6LWKpHeTr/c5Fdld25hvWwg4W7+Ai6xEuuj6Rp8OExBRgjFO8ow+ASt22bF8w==;EndpointSuffix=core.windows.net"
export container_name="exlpoc"
export account_url="https://exlpoc.blob.core.windows.net"
export credential="Srz4Z3s0MOBtupU6/Vk1XbJXC6LWKpHeTr/c5Fdld25hvWwg4W7+Ai6xEuuj6Rp8OExBRgjFO8ow+ASt22bF8w=="
export GOOGLE_APPLICATION_CREDENTIALS="/home/ec2-user/cloud_upload_ori/config/credentials/exlhackathon-355603-b1982fd10722.json"
export bucket_name='dhanuja_buck'
export location='US'
export storage_class='COLDLINE'
export aws_access_key_id='AKIA3ZEX77RMRHQBDBUQ'
export aws_secret_access_key='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'
export bucket_name_aws="in-done"